export const Questions = [
    {
      prompt: "Who was the 1st ODI captain for India?",
      optionA: "Ajit Wadekar",
      optionB: "Bishen Singh Bedi",
      optionC: "Nawab Pataudi",
      optionD: "Vinoo Mankad",
      answer: "optionA",
    },
    {
      prompt: "Which is known as 'Garden City of India?",
      optionA: "Udaipur",
      optionB: "Ujjain",
      optionC: "Shimla",
      optionD: "Bengaluru",
      answer: "optionD",
    },
    {
      prompt: "Where olive ridley turtles are mostly found in India?",
      optionA: "Gujarat",
      optionB: "Andhra Pradesh",
      optionC: "Odisha",
      optionD: "Kerala",
      answer: "optionC",
    },
    {
      prompt: "Where was India's first public sector steel plant set up?",
      optionA: "Rourkela",
      optionB: "Durgapur",
      optionC: "Bhillai",
      optionD: "Aurangabad",
      answer: "optionA",
    },
    {
      prompt: "Which of this is not a programming language?",
      optionA: "Python",
      optionB: "JavaScript",
      optionC: "MC-03",
      optionD: "Java",
      answer: "optionC",
    },
    {
      prompt: "Which of this is not a javascript framework?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Vue",
      optionD: "Java",
      answer: "optionD",
    },
  ];